// Generated by Haxe 4.3.7
(function ($global) { "use strict";
var Main = function() {
	console.log("Main.hx:7:","(ﾟ∀ﾟ)ｱﾋｬ");
	var x = 342;
	var y = 123;
	console.log("Main.hx:12:","x: " + x + ", y: " + y);
	if(x == 342) {
		console.log("Main.hx:16:","x is 342");
	} else {
		console.log("Main.hx:18:","x is something else");
	}
	if(y > 100) {
		console.log("Main.hx:22:","y is greater than 100");
	} else {
		console.log("Main.hx:24:","y is 100 or less");
	}
};
Main.main = function() {
	new Main();
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
Main.main();
})({});
