// Generated by Haxe 4.3.7
(function ($global) { "use strict";
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var HxOverrides = function() { };
HxOverrides.__name__ = true;
HxOverrides.substr = function(s,pos,len) {
	if(len == null) {
		len = s.length;
	} else if(len < 0) {
		if(pos == 0) {
			len = s.length + len;
		} else {
			return "";
		}
	}
	return s.substr(pos,len);
};
HxOverrides.now = function() {
	return Date.now();
};
var Main = function() { };
Main.__name__ = true;
Main.main = function() {
	window.onload = function(_) {
		var canvas = js_Boot.__cast(window.document.getElementById("gameCanvas") , HTMLCanvasElement);
		Main.ctx = canvas.getContext("2d",null);
		window.addEventListener("keydown",Main.onKeyDown);
		window.addEventListener("keyup",Main.onKeyUp);
		canvas.addEventListener("touchstart",Main.onTouchStart);
		canvas.addEventListener("touchend",Main.onTouchEnd);
		Main.generateChart();
		Main.startTime = window.performance.now();
		Main.loop();
	};
};
Main.onTouchStart = function(e) {
	var rect = e.target.getBoundingClientRect();
	var _g = 0;
	var _g1 = e.changedTouches;
	while(_g < _g1.length) {
		var l = (_g1[_g++].clientX - rect.left - 200) / 100 | 0;
		if(l >= 0 && l < 4) {
			if(!Main.keys[l]) {
				Main.keys[l] = true;
				if(!Main.botMode) {
					Main.checkHit(l);
				}
			}
		}
	}
};
Main.onTouchEnd = function(_) {
	Main.keys[0] = false;
	Main.keys[1] = false;
	Main.keys[2] = false;
	Main.keys[3] = false;
};
Main.onKeyDown = function(e) {
	if(e.keyCode == 32) {
		Main.botMode = !Main.botMode;
		return;
	}
	if(e.keyCode == 13) {
		Main.upsideDown = !Main.upsideDown;
		return;
	}
	var l = Main.getLane(e.keyCode);
	if(l != -1 && !Main.keys[l] && !Main.botMode) {
		Main.keys[l] = true;
		Main.checkHit(l);
	}
};
Main.onKeyUp = function(e) {
	var l = Main.getLane(e.keyCode);
	if(l != -1) {
		Main.keys[l] = false;
	}
};
Main.getLane = function(c) {
	switch(c) {
	case 37:
		return 0;
	case 38:
		return 2;
	case 39:
		return 3;
	case 40:
		return 1;
	default:
		return -1;
	}
};
Main.generateChart = function() {
	var t = 3000.0;
	var _g = 0;
	while(_g < 3000) {
		var i = _g++;
		var lane = Math.floor(Math.abs(Math.sin(i * 1.27) * 4)) % 4;
		var interval = 260 + Math.cos(i * 0.75) * 100;
		if(i % 6 == 0) {
			interval += 120;
		}
		var len = i % 7 == 0 ? 320 + Math.random() * 380 : 0;
		Main.chart.push({ t : t, l : lane, hit : false, len : len, holding : false, tailHit : false});
		t += interval;
	}
};
Main.checkHit = function(l) {
	var now = window.performance.now() - Main.startTime;
	var best = null;
	var bestDiff = 9999.0;
	var _g = 0;
	var _g1 = Main.chart;
	while(_g < _g1.length) {
		var n = _g1[_g];
		++_g;
		if(n.hit) {
			continue;
		}
		if(n.l != l) {
			continue;
		}
		var d = Math.abs(n.t - now);
		if(d < bestDiff) {
			bestDiff = d;
			best = n;
		}
	}
	if(best != null && bestDiff < 160) {
		Main.hitHead(best,bestDiff);
	}
};
Main.hitHead = function(n,d) {
	n.hit = true;
	if(n.len > 0) {
		n.holding = true;
	}
	if(d < 45) {
		Main.score += 500;
		Main.combo++;
		Main.life += 1.2;
		Main.rate("SICK","#00FFFF");
	} else if(d < 90) {
		Main.score += 200;
		Main.combo++;
		Main.life += 0.8;
		Main.rate("GOOD","#00FF66");
	} else {
		Main.score += 80;
		Main.combo++;
		Main.life += 0.4;
		Main.rate("BAD","#FF8800");
	}
	if(Main.life > 100) {
		Main.life = 100;
	}
	Main.hitWave[n.l] = 1;
	Main.laneGlow[n.l] = 1;
};
Main.hitTail = function(n) {
	if(!n.tailHit) {
		n.tailHit = true;
		Main.score += 150;
		Main.combo++;
		Main.life += 0.5;
		Main.rate("HOLD","#66CCFF");
	}
};
Main.rate = function(s,c) {
	Main.ratingStr = s;
	Main.ratingColor = c;
	Main.ratingScale = 1.4;
	Main.ratingAlpha = 1;
};
Main.loop = function() {
	window.requestAnimationFrame(function(t) {
		Main.update(t);
		Main.loop();
	});
};
Main.update = function(t) {
	var e = t - Main.startTime;
	Main.ctx.setTransform(1,0,0,1,0,0);
	Main.ctx.fillStyle = "#000";
	Main.ctx.fillRect(0,0,800,600);
	var colors = ["#C24B99","#00FFFF","#12FA05","#F9393F"];
	var judgeY = Main.upsideDown ? 100 : 500;
	if(Main.botMode) {
		var _g = 0;
		var _g1 = Main.chart;
		while(_g < _g1.length) {
			var n = _g1[_g];
			++_g;
			if(!n.hit && n.t <= e) {
				Main.hitHead(n,0);
			}
		}
	}
	Main.ctx.fillStyle = "#FFF";
	Main.ctx.font = "bold 22px Arial";
	Main.ctx.fillText("SCORE " + Main.score,20,40);
	Main.ctx.fillText("COMBO " + Main.combo,20,65);
	var g = Main.ctx.createLinearGradient(20,0,220,0);
	g.addColorStop(0,"#00FF88");
	g.addColorStop(1,"#00FFFF");
	Main.ctx.fillStyle = "#111";
	Main.ctx.fillRect(20,80,200,10);
	Main.ctx.fillStyle = g;
	Main.ctx.fillRect(20,80,200 * (Main.life / 100),10);
	if(Main.ratingAlpha > 0) {
		Main.ctx.save();
		Main.ctx.globalAlpha = Main.ratingAlpha;
		Main.ctx.translate(400,300);
		Main.ctx.scale(Main.ratingScale,Main.ratingScale);
		Main.ctx.fillStyle = Main.ratingColor;
		Main.ctx.textAlign = "center";
		Main.ctx.font = "bold 36px Arial";
		Main.ctx.fillText(Main.ratingStr,0,0);
		Main.ctx.restore();
		Main.ratingScale *= 0.9;
		Main.ratingAlpha *= 0.9;
	}
	var _g = 0;
	while(_g < 4) {
		var i = _g++;
		var lx = 200 + i * 100;
		if(Main.laneGlow[i] > 0) {
			Main.ctx.fillStyle = "rgba(" + Main.hex(colors[i]) + "," + Main.laneGlow[i] * 0.2 + ")";
			Main.ctx.fillRect(lx,0,100,600);
			Main.laneGlow[i] *= 0.9;
		}
		if(Main.hitWave[i] > 0) {
			Main.ctx.beginPath();
			Main.ctx.arc(lx + 50,judgeY + 40,50 * (1 - Main.hitWave[i]),0,Math.PI * 2);
			Main.ctx.strokeStyle = "rgba(" + Main.hex(colors[i]) + "," + Main.hitWave[i] + ")";
			Main.ctx.lineWidth = 4;
			Main.ctx.stroke();
			Main.hitWave[i] *= 0.85;
		}
		Main.ctx.strokeStyle = Main.keys[i] ? "#FFF" : colors[i];
		Main.ctx.lineWidth = Main.keys[i] ? 10 : 3;
		Main.ctx.strokeRect(lx + 10,judgeY,80,80);
	}
	var _g = 0;
	var _g1 = Main.chart;
	while(_g < _g1.length) {
		var n = _g1[_g];
		++_g;
		var diff = n.t - e;
		var y = Main.upsideDown ? judgeY + diff * Main.speed : judgeY - diff * Main.speed;
		if(y < -800 || y > 1200) {
			continue;
		}
		if(n.len > 0) {
			var end = n.t + n.len;
			if(end > e) {
				var h = n.len * Main.speed;
				Main.ctx.fillStyle = "rgba(" + Main.hex(colors[n.l]) + ",0.4)";
				Main.ctx.fillRect(235 + n.l * 100,Main.upsideDown ? y : y - h,30,h);
				if(n.holding && Main.keys[n.l]) {
					if(Math.abs(end - e) < 120) {
						Main.hitTail(n);
					}
				}
			}
		}
		if(!n.hit) {
			Main.ctx.fillStyle = colors[n.l];
			Main.ctx.fillRect(210 + n.l * 100,y,80,25);
		}
		if(!n.hit && (Main.upsideDown ? y < -50 : y > 650)) {
			n.hit = true;
			Main.combo = 0;
			Main.life -= 5;
			Main.rate("MISS","#FF2222");
		}
	}
};
Main.hex = function(h) {
	return Std.parseInt("0x" + HxOverrides.substr(h,1,2)) + "," + Std.parseInt("0x" + HxOverrides.substr(h,3,2)) + "," + Std.parseInt("0x" + HxOverrides.substr(h,5,2));
};
Math.__name__ = true;
var Std = function() { };
Std.__name__ = true;
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
Std.parseInt = function(x) {
	var v = parseInt(x);
	if(isNaN(v)) {
		return null;
	}
	return v;
};
var haxe_Exception = function(message,previous,native) {
	Error.call(this,message);
	this.message = message;
	this.__previousException = previous;
	this.__nativeException = native != null ? native : this;
};
haxe_Exception.__name__ = true;
haxe_Exception.thrown = function(value) {
	if(((value) instanceof haxe_Exception)) {
		return value.get_native();
	} else if(((value) instanceof Error)) {
		return value;
	} else {
		var e = new haxe_ValueException(value);
		return e;
	}
};
haxe_Exception.__super__ = Error;
haxe_Exception.prototype = $extend(Error.prototype,{
	get_native: function() {
		return this.__nativeException;
	}
	,__class__: haxe_Exception
});
var haxe_ValueException = function(value,previous,native) {
	haxe_Exception.call(this,String(value),previous,native);
	this.value = value;
};
haxe_ValueException.__name__ = true;
haxe_ValueException.__super__ = haxe_Exception;
haxe_ValueException.prototype = $extend(haxe_Exception.prototype,{
	__class__: haxe_ValueException
});
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.__name__ = true;
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
	,__class__: haxe_iterators_ArrayIterator
};
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.getClass = function(o) {
	if(o == null) {
		return null;
	} else if(((o) instanceof Array)) {
		return Array;
	} else {
		var cl = o.__class__;
		if(cl != null) {
			return cl;
		}
		var name = js_Boot.__nativeClassName(o);
		if(name != null) {
			return js_Boot.__resolveNativeClass(name);
		}
		return null;
	}
};
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(((o) instanceof Array)) {
			var str = "[";
			s += "\t";
			var _g = 0;
			var _g1 = o.length;
			while(_g < _g1) {
				var i = _g++;
				str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
			}
			str += "]";
			return str;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( _g ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var str = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		var k = null;
		for( k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str.length != 2) {
			str += ", \n";
		}
		str += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str += "\n" + s + "}";
		return str;
	case "string":
		return o;
	default:
		return String(o);
	}
};
js_Boot.__interfLoop = function(cc,cl) {
	while(true) {
		if(cc == null) {
			return false;
		}
		if(cc == cl) {
			return true;
		}
		var intf = cc.__interfaces__;
		if(intf != null) {
			var _g = 0;
			var _g1 = intf.length;
			while(_g < _g1) {
				var i = intf[_g++];
				if(i == cl || js_Boot.__interfLoop(i,cl)) {
					return true;
				}
			}
		}
		cc = cc.__super__;
	}
};
js_Boot.__instanceof = function(o,cl) {
	if(cl == null) {
		return false;
	}
	switch(cl) {
	case Array:
		return ((o) instanceof Array);
	case Bool:
		return typeof(o) == "boolean";
	case Dynamic:
		return o != null;
	case Float:
		return typeof(o) == "number";
	case Int:
		if(typeof(o) == "number") {
			return ((o | 0) === o);
		} else {
			return false;
		}
		break;
	case String:
		return typeof(o) == "string";
	default:
		if(o != null) {
			if(typeof(cl) == "function") {
				if(js_Boot.__downcastCheck(o,cl)) {
					return true;
				}
			} else if(typeof(cl) == "object" && js_Boot.__isNativeObj(cl)) {
				if(((o) instanceof cl)) {
					return true;
				}
			}
		} else {
			return false;
		}
		if(cl == Class ? o.__name__ != null : false) {
			return true;
		}
		if(cl == Enum ? o.__ename__ != null : false) {
			return true;
		}
		return false;
	}
};
js_Boot.__downcastCheck = function(o,cl) {
	if(!((o) instanceof cl)) {
		if(cl.__isInterface__) {
			return js_Boot.__interfLoop(js_Boot.getClass(o),cl);
		} else {
			return false;
		}
	} else {
		return true;
	}
};
js_Boot.__cast = function(o,t) {
	if(o == null || js_Boot.__instanceof(o,t)) {
		return o;
	} else {
		throw haxe_Exception.thrown("Cannot cast " + Std.string(o) + " to " + Std.string(t));
	}
};
js_Boot.__nativeClassName = function(o) {
	var name = js_Boot.__toStr.call(o).slice(8,-1);
	if(name == "Object" || name == "Function" || name == "Math" || name == "JSON") {
		return null;
	}
	return name;
};
js_Boot.__isNativeObj = function(o) {
	return js_Boot.__nativeClassName(o) != null;
};
js_Boot.__resolveNativeClass = function(name) {
	return $global[name];
};
if(typeof(performance) != "undefined" ? typeof(performance.now) == "function" : false) {
	HxOverrides.now = performance.now.bind(performance);
}
Object.defineProperty(String.prototype,"__class__",{ value : String, enumerable : false, writable : true});
String.__name__ = true;
Array.__name__ = true;
var Int = { };
var Dynamic = { };
var Float = Number;
var Bool = Boolean;
var Class = { };
var Enum = { };
js_Boot.__toStr = ({ }).toString;
Main.chart = [];
Main.startTime = 0;
Main.speed = 0.7;
Main.keys = [false,false,false,false];
Main.score = 0;
Main.combo = 0;
Main.life = 100;
Main.botMode = false;
Main.upsideDown = false;
Main.ratingStr = "";
Main.ratingScale = 0;
Main.ratingColor = "#FFF";
Main.ratingAlpha = 0;
Main.hitWave = [0.0,0.0,0.0,0.0];
Main.laneGlow = [0.0,0.0,0.0,0.0];
Main.main();
})(typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);
