// Generated by Haxe 4.3.7
(function ($global) { "use strict";
class Main {
	constructor() {
		this.isGameOver = false;
		this.maxAttempts = 10;
		this.attempts = 0;
		this.secretNumber = Std.random(50) + 1;
		console.log("Main.hx:14:","====== 数字当てゲーム ======");
		console.log("Main.hx:15:","1から50の間の数字を当ててください！");
		console.log("Main.hx:16:","試行回数制限: " + this.maxAttempts + "回");
		console.log("Main.hx:17:","----------------------------");
		this.askForGuess();
	}
	askForGuess() {
		if(this.isGameOver) {
			return;
		}
		let _gthis = this;
		window.setTimeout(function() {
			let result = window.prompt("1〜50の数字を入力してください（残り " + (_gthis.maxAttempts - _gthis.attempts) + " 回）:");
			if(result == null) {
				console.log("Main.hx:33:","ゲームがキャンセルされました。");
				_gthis.isGameOver = true;
				return;
			}
			let inputInt = Std.parseInt(result);
			if(inputInt == null) {
				console.log("Main.hx:40:","❌ エラー: 有効な数字を入力してください。");
				_gthis.askForGuess();
				return;
			}
			_gthis.guess(inputInt);
		},10);
	}
	guess(input) {
		if(input < 1 || input > 50) {
			console.log("Main.hx:52:","❌ エラー: 1から50の間の数字を入力してください");
			this.askForGuess();
			return;
		}
		this.attempts++;
		if(input == this.secretNumber) {
			console.log("Main.hx:61:","🎉 正解です！ 数字は " + this.secretNumber + " でした");
			console.log("Main.hx:62:","試行回数: " + this.attempts + "回");
			this.isGameOver = true;
		} else if(input < this.secretNumber) {
			console.log("Main.hx:65:","🔼 " + input + " より【大きい】数字です");
			console.log("Main.hx:66:","残り試行回数: " + (this.maxAttempts - this.attempts) + "回");
		} else {
			console.log("Main.hx:68:","🔽 " + input + " より【小さい】数字です");
			console.log("Main.hx:69:","残り試行回数: " + (this.maxAttempts - this.attempts) + "回");
		}
		if(this.attempts >= this.maxAttempts && !this.isGameOver) {
			console.log("Main.hx:74:","💥 ゲームオーバー。正解は " + this.secretNumber + " でした。");
			this.isGameOver = true;
		}
		if(!this.isGameOver) {
			this.askForGuess();
		}
	}
	static main() {
		new Main();
	}
}
class Std {
	static parseInt(x) {
		let v = parseInt(x);
		if(isNaN(v)) {
			return null;
		}
		return v;
	}
	static random(x) {
		if(x <= 0) {
			return 0;
		} else {
			return Math.floor(Math.random() * x);
		}
	}
}
class haxe_iterators_ArrayIterator {
	constructor(array) {
		this.current = 0;
		this.array = array;
	}
	hasNext() {
		return this.current < this.array.length;
	}
	next() {
		return this.array[this.current++];
	}
}
{
}
Main.main();
})({});
