// Generated by Haxe 4.3.3
(function ($global) { "use strict";
var Main = function() { };
Main.main = function() {
	var canvas = window.document.createElement("canvas");
	canvas.width = 400;
	canvas.height = 300;
	window.document.body.appendChild(canvas);
	var ctx = canvas.getContext("2d",null);
	var x = 0;
	var loop = null;
	loop = function(_) {
		ctx.clearRect(0,0,400,300);
		ctx.fillStyle = "red";
		ctx.fillRect(x,120,40,40);
		x = (x + 2) % 400;
		window.requestAnimationFrame(loop);
	};
	loop(null);
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
Main.main();
})({});
