// Generated by Haxe 4.3.7
(function ($global) { "use strict";
var Main = function() { };
Main.main = function() {
	console.log("Main.hx:3:","Hello, World!");
};
Main.main();
})(typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);
