// Generated by Haxe 4.3.7
(function ($global) { "use strict";
var Main = function() { };
Main.main = function() {
	window.onload = function() {
		var canvas = window.document.getElementById("clockCanvas");
		var ctx = canvas.getContext("2d",null);
		var update = null;
		update = function(t) {
			Main.drawClock(ctx,canvas.width,canvas.height);
			window.requestAnimationFrame(update);
		};
		window.requestAnimationFrame(update);
	};
};
Main.drawClock = function(ctx,w,h) {
	var date = new Date();
	var radius = Math.min(w,h) / 2 * 0.9;
	var cx = w / 2;
	var cy = h / 2;
	ctx.clearRect(0,0,w,h);
	ctx.beginPath();
	ctx.arc(cx,cy,radius,0,2 * Math.PI);
	ctx.strokeStyle = "#333";
	ctx.lineWidth = 5;
	ctx.stroke();
	var _g = 0;
	while(_g < 60) {
		var i = _g++;
		var angle = i / 60 * 2 * Math.PI - Math.PI / 2;
		var outer = radius * 0.95;
		var inner = i % 5 == 0 ? radius * 0.85 : radius * 0.90;
		ctx.beginPath();
		ctx.lineWidth = i % 5 == 0 ? 4 : 2;
		ctx.strokeStyle = "#000";
		ctx.moveTo(cx + Math.cos(angle) * inner,cy + Math.sin(angle) * inner);
		ctx.lineTo(cx + Math.cos(angle) * outer,cy + Math.sin(angle) * outer);
		ctx.stroke();
	}
	var hand = function(value,max,len,width,color) {
		var angle = value / max * 2 * Math.PI - Math.PI / 2;
		ctx.beginPath();
		ctx.lineWidth = width;
		ctx.lineCap = "round";
		ctx.strokeStyle = color;
		ctx.moveTo(cx,cy);
		ctx.lineTo(cx + Math.cos(angle) * len,cy + Math.sin(angle) * len);
		ctx.stroke();
	};
	var sec = date.getSeconds();
	var min = date.getMinutes() + sec / 60;
	hand(date.getHours() % 12 + min / 60,12,radius * 0.5,6,"#000");
	hand(min,60,radius * 0.75,4,"#444");
	hand(sec,60,radius * 0.85,2,"#d00");
	ctx.beginPath();
	ctx.arc(cx,cy,6,0,2 * Math.PI);
	ctx.fillStyle = "#000";
	ctx.fill();
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
Main.main();
})({});
