// Generated by Haxe 4.3.7
(function ($global) { "use strict";
var Main = function() { };
Main.main = function() {
	Main.canvas = window.document.getElementById("game");
	if(Main.canvas == null) {
		Main.canvas = window.document.createElement("canvas");
		Main.canvas.id = "game";
		Main.canvas.width = Main.WIDTH;
		Main.canvas.height = Main.HEIGHT;
		window.document.body.appendChild(Main.canvas);
	} else {
		Main.canvas.width = Main.WIDTH;
		Main.canvas.height = Main.HEIGHT;
	}
	Main.ctx = Main.canvas.getContext("2d",null);
	Main.initGame();
	Main.setupInput();
	window.requestAnimationFrame(Main.loop);
};
Main.initGame = function() {
	Main.ballX = Main.WIDTH / 2;
	Main.ballY = Main.HEIGHT / 2;
	Main.ballVX = 4;
	Main.ballVY = -4;
	Main.paddleX = Main.WIDTH / 2 - Main.paddleWidth / 2;
	Main.paddleY = Main.HEIGHT - 40;
	Main.brickWidth = (Main.WIDTH - Main.brickOffsetLeft * 2 - Main.brickPadding * (Main.cols - 1)) / Main.cols;
	Main.bricks = [];
	var _g = 0;
	var _g1 = Main.rows;
	while(_g < _g1) {
		var r = _g++;
		var row = [];
		var _g2 = 0;
		var _g3 = Main.cols;
		while(_g2 < _g3) {
			var c = _g2++;
			row.push(true);
		}
		Main.bricks.push(row);
	}
	Main.score = 0;
	Main.lives = 3;
	Main.isGameOver = false;
	Main.isClear = false;
	Main.isPaused = false;
};
Main.resetBallAndPaddle = function() {
	Main.ballX = Main.WIDTH / 2;
	Main.ballY = Main.HEIGHT / 2;
	Main.ballVX = 4;
	Main.ballVY = -4;
	Main.paddleX = Main.WIDTH / 2 - Main.paddleWidth / 2;
	Main.paddleY = Main.HEIGHT - 40;
};
Main.setupInput = function() {
	window.addEventListener("keydown",function(e) {
		switch(e.key) {
		case " ":
			Main.isPaused = !Main.isPaused;
			break;
		case "ArrowLeft":
			Main.moveLeft = true;
			break;
		case "ArrowRight":
			Main.moveRight = true;
			break;
		case "R":case "r":
			if(Main.isGameOver || Main.isClear) {
				Main.initGame();
			}
			break;
		default:
		}
	});
	window.addEventListener("keyup",function(e) {
		switch(e.key) {
		case "ArrowLeft":
			Main.moveLeft = false;
			break;
		case "ArrowRight":
			Main.moveRight = false;
			break;
		default:
		}
	});
	Main.canvas.addEventListener("mousemove",function(e) {
		var rect = Main.canvas.getBoundingClientRect();
		var mouseX = e.clientX - rect.left;
		Main.paddleX = mouseX - Main.paddleWidth / 2;
		if(Main.paddleX < 0) {
			Main.paddleX = 0;
		}
		if(Main.paddleX + Main.paddleWidth > Main.WIDTH) {
			Main.paddleX = Main.WIDTH - Main.paddleWidth;
		}
	});
};
Main.loop = function(_time) {
	Main.update();
	Main.draw();
	window.requestAnimationFrame(Main.loop);
};
Main.update = function() {
	if(Main.isGameOver || Main.isClear || Main.isPaused) {
		return;
	}
	if(Main.moveLeft) {
		Main.paddleX -= Main.paddleSpeed;
	}
	if(Main.moveRight) {
		Main.paddleX += Main.paddleSpeed;
	}
	if(Main.paddleX < 0) {
		Main.paddleX = 0;
	}
	if(Main.paddleX + Main.paddleWidth > Main.WIDTH) {
		Main.paddleX = Main.WIDTH - Main.paddleWidth;
	}
	Main.ballX += Main.ballVX;
	Main.ballY += Main.ballVY;
	if(Main.ballX - Main.ballRadius < 0) {
		Main.ballX = Main.ballRadius;
		Main.ballVX *= -1;
	} else if(Main.ballX + Main.ballRadius > Main.WIDTH) {
		Main.ballX = Main.WIDTH - Main.ballRadius;
		Main.ballVX *= -1;
	}
	if(Main.ballY - Main.ballRadius < 0) {
		Main.ballY = Main.ballRadius;
		Main.ballVY *= -1;
	}
	if(Main.ballY + Main.ballRadius >= Main.paddleY && Main.ballY + Main.ballRadius <= Main.paddleY + Main.paddleHeight && Main.ballX >= Main.paddleX && Main.ballX <= Main.paddleX + Main.paddleWidth) {
		Main.ballY = Main.paddleY - Main.ballRadius;
		Main.ballVY *= -1;
		var hitPos = (Main.ballX - (Main.paddleX + Main.paddleWidth / 2)) / (Main.paddleWidth / 2);
		Main.ballVX = hitPos * 6;
	}
	if(Main.ballY - Main.ballRadius > Main.HEIGHT) {
		Main.lives--;
		if(Main.lives <= 0) {
			Main.isGameOver = true;
		} else {
			Main.resetBallAndPaddle();
		}
	}
	Main.checkBrickCollision();
	if(Main.isAllBricksCleared()) {
		Main.isClear = true;
	}
};
Main.checkBrickCollision = function() {
	var _g = 0;
	var _g1 = Main.rows;
	while(_g < _g1) {
		var r = _g++;
		var _g2 = 0;
		var _g3 = Main.cols;
		while(_g2 < _g3) {
			var c = _g2++;
			if(!Main.bricks[r][c]) {
				continue;
			}
			var bx = Main.brickOffsetLeft + c * (Main.brickWidth + Main.brickPadding);
			var by = Main.brickOffsetTop + r * (Main.brickHeight + Main.brickPadding);
			var bw = Main.brickWidth;
			var bh = Main.brickHeight;
			if(Main.circleRectCollision(Main.ballX,Main.ballY,Main.ballRadius,bx,by,bw,bh)) {
				Main.bricks[r][c] = false;
				Main.score += 10;
				var ballCenterY = Main.ballY;
				if(ballCenterY < by || ballCenterY > by + bh) {
					Main.ballVY *= -1;
				} else {
					Main.ballVX *= -1;
				}
				return;
			}
		}
	}
};
Main.circleRectCollision = function(cx,cy,cr,rx,ry,rw,rh) {
	var max = rx + rw;
	var closestX = cx < rx ? rx : cx > max ? max : cx;
	var max = ry + rh;
	var closestY = cy < ry ? ry : cy > max ? max : cy;
	var dx = cx - closestX;
	var dy = cy - closestY;
	return dx * dx + dy * dy <= cr * cr;
};
Main.clamp = function(v,min,max) {
	if(v < min) {
		return min;
	} else if(v > max) {
		return max;
	} else {
		return v;
	}
};
Main.isAllBricksCleared = function() {
	var _g = 0;
	var _g1 = Main.rows;
	while(_g < _g1) {
		var r = _g++;
		var _g2 = 0;
		var _g3 = Main.cols;
		while(_g2 < _g3) {
			var c = _g2++;
			if(Main.bricks[r][c]) {
				return false;
			}
		}
	}
	return true;
};
Main.draw = function() {
	Main.ctx.fillStyle = "#111";
	Main.ctx.fillRect(0,0,Main.WIDTH,Main.HEIGHT);
	var _g = 0;
	var _g1 = Main.rows;
	while(_g < _g1) {
		var r = _g++;
		var _g2 = 0;
		var _g3 = Main.cols;
		while(_g2 < _g3) {
			var c = _g2++;
			if(!Main.bricks[r][c]) {
				continue;
			}
			var x = Main.brickOffsetLeft + c * (Main.brickWidth + Main.brickPadding);
			var y = Main.brickOffsetTop + r * (Main.brickHeight + Main.brickPadding);
			Main.ctx.fillStyle = Main.getBrickColor(r);
			Main.ctx.fillRect(x,y,Main.brickWidth,Main.brickHeight);
		}
	}
	Main.ctx.fillStyle = "#eee";
	Main.ctx.fillRect(Main.paddleX,Main.paddleY,Main.paddleWidth,Main.paddleHeight);
	Main.ctx.beginPath();
	Main.ctx.arc(Main.ballX,Main.ballY,Main.ballRadius,0,Math.PI * 2);
	Main.ctx.fillStyle = "#ffcc00";
	Main.ctx.fill();
	Main.ctx.closePath();
	Main.ctx.fillStyle = "#fff";
	Main.ctx.font = "20px sans-serif";
	Main.ctx.fillText("Score: " + Main.score,20,30);
	Main.ctx.fillText("Lives: " + Main.lives,Main.WIDTH - 120,30);
	if(Main.isPaused) {
		Main.drawCenterText("PAUSED (Space)","#ffff88");
	}
	if(Main.isGameOver) {
		Main.drawCenterText("GAME OVER - Press R","#ff6666");
	} else if(Main.isClear) {
		Main.drawCenterText("CLEAR!! - Press R","#66ff99");
	}
};
Main.drawCenterText = function(text,color) {
	Main.ctx.fillStyle = color;
	Main.ctx.font = "32px sans-serif";
	var metrics = Main.ctx.measureText(text);
	var textWidth = metrics.width;
	Main.ctx.fillText(text,(Main.WIDTH - textWidth) / 2,Main.HEIGHT / 2);
};
Main.getBrickColor = function(row) {
	switch(row) {
	case 0:
		return "#ff6666";
	case 1:
		return "#ff9966";
	case 2:
		return "#ffcc66";
	case 3:
		return "#99ff66";
	case 4:
		return "#66ccff";
	case 5:
		return "#cc66ff";
	default:
		return "#ffffff";
	}
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
Main.WIDTH = 800;
Main.HEIGHT = 600;
Main.ballRadius = 8;
Main.paddleWidth = 100;
Main.paddleHeight = 16;
Main.paddleSpeed = 8;
Main.moveLeft = false;
Main.moveRight = false;
Main.cols = 10;
Main.rows = 6;
Main.brickHeight = 24;
Main.brickPadding = 4;
Main.brickOffsetTop = 60;
Main.brickOffsetLeft = 40;
Main.score = 0;
Main.lives = 3;
Main.isGameOver = false;
Main.isClear = false;
Main.isPaused = false;
Main.main();
})({});
